// frontend/smartknora/src/views/auth/RegisterPage.vue
<template>
  <div class="register-container">
    <div class="register-card">
      <h2 class="register-title">注册账号</h2>
      <div class="form-area">
        <t-input v-model="form.phone" placeholder="手机号" :maxlength="11" @input="(v:string)=>form.phone=v.replace(/\D/g,'').slice(0,11)">
          <template #prefix-icon><t-icon name="user" /></template>
        </t-input>
        <t-input v-model="form.nickname" placeholder="昵称（选填）">
          <template #prefix-icon><t-icon name="user-circle" /></template>
        </t-input>
        <t-input v-model="form.password" type="password" placeholder="密码（至少6位）">
          <template #prefix-icon><t-icon name="lock-on" /></template>
        </t-input>
        <t-input v-model="form.confirmPassword" type="password" placeholder="确认密码">
          <template #prefix-icon><t-icon name="lock-on" /></template>
        </t-input>
        <t-checkbox v-model="agreed">
          我已阅读并同意 <t-link theme="primary">《服务协议》</t-link> 和 <t-link theme="primary">《隐私政策》</t-link>
        </t-checkbox>
        <t-button theme="primary" block size="large" :loading="loading" :disabled="!agreed || !form.phone || !form.password || form.password !== form.confirmPassword" @click="handleRegister">
          注册
        </t-button>
      </div>
      <div class="login-link">
        已有账号？<t-link theme="primary" @click="$router.push('/login')">返回登录</t-link>
      </div>
      <t-message v-if="errorMsg" theme="error" style="margin-top:12px">{{ errorMsg }}</t-message>
      <t-message v-if="successMsg" theme="success" style="margin-top:12px">{{ successMsg }}</t-message>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { register } from '@/api/auth'
import { useAuthStore } from '@/stores/auth'
import { MessagePlugin } from 'tdesign-vue-next'

const router = useRouter()
const authStore = useAuthStore()
const agreed = ref(true)
const loading = ref(false)
const errorMsg = ref('')
const successMsg = ref('')
const form = ref({ phone: '', nickname: '', password: '', confirmPassword: '' })

async function handleRegister() {
  if (form.value.password !== form.value.confirmPassword) { errorMsg.value = '两次密码不一致'; return }
  if (form.value.password.length < 6) { errorMsg.value = '密码至少6位'; return }
  loading.value = true; errorMsg.value = ''; successMsg.value = ''
  try {
    const res = await register({ phone: form.value.phone, password: form.value.password, nickname: form.value.nickname })
    authStore.setAuth(res.data)
    MessagePlugin.success('注册成功，欢迎加入！')
    router.push('/spaces')
  } catch (e: any) {
    errorMsg.value = e.response?.data?.error || '注册失败'
  } finally { loading.value = false }
}
</script>
<style scoped>
.register-container { display: flex; align-items: center; justify-content: center; min-height: 100vh; background: linear-gradient(135deg, #014DB2 0%, #0A7AFF 100%); }
.register-card { width: 420px; background: #fff; border-radius: 12px; padding: 40px 36px; box-shadow: 0 4px 24px rgba(0,0,0,0.15); }
.register-title { font-size: 24px; font-weight: 600; color: #0a1628; margin-bottom: 24px; text-align: center; }
.form-area { display: flex; flex-direction: column; gap: 16px; }
.login-link { margin-top: 16px; text-align: center; font-size: 14px; color: #666; }
</style>

// frontend/smartknora-react-backup/src/pages/auth/RegisterPage.tsx
import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Form, Input, Button, MessagePlugin, Tabs } from 'tdesign-react'
import { useAuthStore } from '../../stores/auth'

export default function RegisterPage() {
  const navigate = useNavigate()
  const { register, isLoading } = useAuthStore()
  const [tab, setTab] = useState<string>('phone')
  const [phone, setPhone] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [nickname, setNickname] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (password !== confirmPassword) {
      MessagePlugin.error('两次密码输入不一致')
      return
    }
    if (password.length < 8) {
      MessagePlugin.error('密码至少需要8位')
      return
    }
    try {
      await register({
        phone: tab === 'phone' ? phone : undefined,
        email: tab === 'email' ? email : undefined,
        password,
        nickname: nickname || undefined,
      })
      MessagePlugin.success('注册成功')
      navigate('/workspace')
    } catch (err: any) {
      MessagePlugin.error(err?.response?.data?.error || '注册失败')
    }
  }

  return (
    <div style={{
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100vh',
      background: '#f5f5f5',
    }}>
      <div style={{
        width: 420,
        background: '#fff',
        borderRadius: 16,
        padding: '40px 32px',
        boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <h1 style={{ fontSize: 28, fontWeight: 600, color: '#0052D9', margin: 0 }}>
            随越·智枢
          </h1>
          <p style={{ fontSize: 14, color: '#8B8B8B', margin: '8px 0 0' }}>
            创建您的账号
          </p>
        </div>

        <Tabs value={tab} onChange={setTab}>
          <Tabs.TabPanel value="phone" label="手机号注册">
            <Form onSubmit={handleSubmit} style={{ marginTop: 24 }}>
              <Form.FormItem>
                <Input placeholder="请输入手机号" value={phone} onChange={setPhone} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Input placeholder="昵称（选填）" value={nickname} onChange={setNickname} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Input type="password" placeholder="密码（至少8位）" value={password} onChange={setPassword} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Input type="password" placeholder="确认密码" value={confirmPassword} onChange={setConfirmPassword} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Button type="submit" theme="primary" size="large" block loading={isLoading}
                  disabled={!phone || !password || !confirmPassword}>
                  注册
                </Button>
              </Form.FormItem>
            </Form>
          </Tabs.TabPanel>

          <Tabs.TabPanel value="email" label="邮箱注册">
            <Form onSubmit={handleSubmit} style={{ marginTop: 24 }}>
              <Form.FormItem>
                <Input placeholder="请输入邮箱" value={email} onChange={setEmail} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Input placeholder="昵称（选填）" value={nickname} onChange={setNickname} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Input type="password" placeholder="密码（至少8位）" value={password} onChange={setPassword} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Input type="password" placeholder="确认密码" value={confirmPassword} onChange={setConfirmPassword} size="large" />
              </Form.FormItem>
              <Form.FormItem>
                <Button type="submit" theme="primary" size="large" block loading={isLoading}
                  disabled={!email || !password || !confirmPassword}>
                  注册
                </Button>
              </Form.FormItem>
            </Form>
          </Tabs.TabPanel>
        </Tabs>

        <div style={{ textAlign: 'center', marginTop: 24, fontSize: 14 }}>
          <span style={{ color: '#999' }}>已有账号？</span>
          <Link to="/login" style={{ color: '#0052D9', marginLeft: 4 }}>立即登录</Link>
        </div>
      </div>
    </div>
  )
}
