// frontend/smartknora-react-backup/src/pages/spaces/DocumentsPage.tsx
import { useEffect, useState } from 'react'
import { Card, Table, Button, Tag, Upload, Dialog, Form, Input, Select, MessagePlugin, Progress } from 'tdesign-react'
import { useParams } from 'react-router-dom'
import client from '../../api/client'

interface Document {
  id: string
  title: string
  file_name: string
  file_type: string
  file_size: number
  parse_status: string
  chunk_count: number
  embedding_status: string
  created_at: string
}

export default function DocumentsPage() {
  const { spaceId } = useParams<{ spaceId: string }>()
  const [docs, setDocs] = useState<Document[]>([])
  const [loading, setLoading] = useState(false)
  const [showUpload, setShowUpload] = useState(false)
  const [search, setSearch] = useState('')

  const loadDocs = () => {
    setLoading(true)
    client.get('/documents', { params: { space_id: spaceId, search } })
      .then(res => setDocs(res.data.documents || []))
      .catch((err) => { console.error('API error:', err) })
      .finally(() => setLoading(false))
  }
  useEffect(() => {
    const timer = setTimeout(() => { loadDocs() }, 300)
    return () => clearTimeout(timer)
  }, [spaceId, search])

  const handleUpload = (file: any) => {
    const formData = new FormData()
    formData.append('file', file)
    formData.append('space_id', spaceId || '')
    client.post('/documents/upload', formData, {
      headers: { 'Content-Type': 'multipart/form-data' }
    }).then(() => {
      MessagePlugin.success('上传成功')
      loadDocs()
    }).catch(err => {
      MessagePlugin.error(err?.response?.data?.error || '上传失败')
    })
    return false // Prevent default upload
  }

  const handleDelete = async (id: string) => {
    const confirmed = await Dialog.confirm({ header: '确认删除', body: '确定要删除此文档吗？删除后无法恢复。' })
    if (confirmed) {
      try {
        await client.delete(`/documents/${id}`)
        MessagePlugin.success('已删除')
        loadDocs()
      } catch (err: any) {
        MessagePlugin.error(err?.response?.data?.error || '删除失败')
      }
    }
  }

  const handleReparse = async (id: string) => {
    try {
      await client.post(`/documents/${id}/reparse`)
      MessagePlugin.success('重新解析已触发')
      loadDocs()
    } catch (err: any) {
      MessagePlugin.error(err?.response?.data?.error || '操作失败')
    }
  }

  const statusColor = (s: string) => {
    switch (s) {
      case 'completed': return 'success'
      case 'parsing': return 'warning'
      case 'failed': return 'danger'
      default: return 'default'
    }
  }

  const columns = [
    { title: '文件名', colKey: 'title', width: 300 },
    { title: '类型', colKey: 'file_type', width: 100, cell: ({ row }: any) => (
      <Tag>{row.file_type?.replace('.', '').toUpperCase()}</Tag>
    )},
    { title: '大小', colKey: 'file_size', width: 100, cell: ({ row }: any) => (
      <span>{(row.file_size / 1024).toFixed(1)} KB</span>
    )},
    { title: '解析状态', colKey: 'parse_status', width: 120, cell: ({ row }: any) => (
      <Tag theme={statusColor(row.parse_status)}>
        {row.parse_status === 'completed' ? '已完成' : row.parse_status === 'parsing' ? '解析中' : row.parse_status === 'failed' ? '失败' : '待处理'}
      </Tag>
    )},
    { title: '分块数', colKey: 'chunk_count', width: 80 },
    { title: '上传时间', colKey: 'created_at', width: 180, cell: ({ row }: any) =>
      new Date(row.created_at).toLocaleString()
    },
    { title: '操作', colKey: 'actions', width: 200, cell: ({ row }: any) => (
      <div style={{ display: 'flex', gap: 8 }}>
        <Button size="small" variant="outline" onClick={() => handleReparse(row.id)}>重新解析</Button>
        <Button size="small" variant="outline" theme="danger" onClick={() => handleDelete(row.id)}>删除</Button>
      </div>
    )},
  ]

  return (
    <div style={{ padding: 24 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <h2 style={{ margin: 0 }}>📄 文档管理</h2>
        <div style={{ display: 'flex', gap: 12 }}>
          <Input placeholder="搜索文档..." value={search} onChange={setSearch} style={{ width: 200 }} />
          <Upload beforeUpload={handleUpload} showUploadList={false}>
            <Button theme="primary">+ 上传文档</Button>
          </Upload>
        </div>
      </div>

      <Card>
        <Table
          data={docs}
          columns={columns}
          rowKey="id"
          loading={loading}
          bordered
          stripe
          pagination={{ pageSize: 20 }}
        />
      </Card>
    </div>
  )
}

// frontend/smartknora/src/views/spaces/DocumentsPage.vue
<template>
  <div class="docs-page">
    <div class="docs-header">
      <div class="header-left">
        <t-button variant="text" @click="$router.push('/spaces')">
          <template #icon><t-icon name="chevron-left" /></template>
          知识空间
        </t-button>
        <h2 v-if="spaceId">空间文档</h2>
      </div>
      <t-space>
        <t-input v-model="searchQuery" placeholder="搜索文档..." clearable style="width:200px" @enter="loadDocuments">
          <template #prefix-icon><t-icon name="search" /></template>
        </t-input>
        <t-select v-model="statusFilter" placeholder="状态" clearable style="width:120px" @change="loadDocuments">
          <t-option value="pending" label="等待中" />
          <t-option value="parsing" label="解析中" />
          <t-option value="completed" label="已完成" />
          <t-option value="failed" label="失败" />
        </t-select>
        <t-button theme="primary" @click="showImport = true">
          <template #icon><t-icon name="upload" /></template>
          导入文档
        </t-button>
      </t-space>
    </div>

    <t-loading v-if="loading" />
    <div v-else-if="documents.length === 0" class="empty">
      <t-icon name="file-paste" size="64px" class="muted-empty-icon" />
      <p class="empty-title">暂无文档</p>
      <p class="empty-desc">上传文件、导入网页或手动录入知识内容</p>
      <t-button theme="primary" @click="showImport = true">导入文档</t-button>
    </div>
    <div v-else class="doc-list">
      <t-table :data="documents" :columns="columns" row-key="id" hover stripe @row-click="onRowClick">
        <template #file_type="{ row }">
          <t-tag theme="default" variant="light">{{ row.file_type || '—' }}</t-tag>
        </template>
        <template #file_size="{ row }">
          {{ formatSize(row.file_size) }}
        </template>
        <template #parse_status="{ row }">
          <t-tag :theme="statusTheme(row.parse_status)" variant="light">
            <template #icon v-if="row.parse_status === 'parsing' || row.parse_status === 'pending'">
              <t-icon name="loading" />
            </template>
            {{ statusLabel(row.parse_status) }}
          </t-tag>
        </template>
        <template #chunk_count="{ row }">
          <t-tag theme="primary" variant="light" size="small">{{ row.chunk_count }} 块</t-tag>
        </template>
        <template #created_at="{ row }">
          {{ formatDate(row.created_at) }}
        </template>
        <template #operation="{ row }">
          <t-space size="small">
            <t-button variant="text" size="small" @click.stop="viewChunks(row)">
              <t-icon name="view-list" /> 分块
            </t-button>
            <t-button variant="text" size="small" theme="warning" @click.stop="handleReparse(row)">
              <t-icon name="refresh" /> 重新解析
            </t-button>
            <t-popconfirm content="确认删除此文档？" @confirm="handleDelete(row)">
              <t-button variant="text" size="small" theme="danger" @click.stop>
                <t-icon name="delete" /> 删除
              </t-button>
            </t-popconfirm>
          </t-space>
        </template>
      </t-table>
      <div class="pagination" v-if="total > pageSize">
        <t-pagination
          v-model="currentPage"
          :total="total"
          :page-size="pageSize"
          show-jumper
          @change="loadDocuments"
        />
      </div>
    </div>

    <DocumentImportDialog
      v-if="showImport"
      v-model:visible="showImport"
      :space-id="spaceId"
      @success="loadDocuments"
    />

    <DocumentChunksDialog
      v-if="showChunks"
      v-model:visible="showChunks"
      :loading="chunksLoading"
      :chunks="chunks"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, defineAsyncComponent, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { listDocuments, deleteDocument, reparseDocument, getDocumentChunks, type Document, type DocumentChunk } from '@/api/documents'
import { MessagePlugin } from 'tdesign-vue-next'

const DocumentImportDialog = defineAsyncComponent(() => import('@/components/documents/DocumentImportDialog.vue'))
const DocumentChunksDialog = defineAsyncComponent(() => import('@/components/documents/DocumentChunksDialog.vue'))

const route = useRoute()
const spaceId = computed(() => (route.params.id as string) || '')

const documents = ref<Document[]>([])
const loading = ref(true)
const searchQuery = ref('')
const statusFilter = ref('')
const currentPage = ref(1)
const pageSize = ref(20)
const total = ref(0)

const showImport = ref(false)
const showChunks = ref(false)
const chunks = ref<DocumentChunk[]>([])
const chunksLoading = ref(false)

const columns = [
  { colKey: 'title', title: '文档名称', ellipsis: true, minWidth: 200 },
  { colKey: 'file_type', title: '类型', width: 80 },
  { colKey: 'file_size', title: '大小', width: 100 },
  { colKey: 'parse_status', title: '状态', width: 100 },
  { colKey: 'chunk_count', title: '分块', width: 80 },
  { colKey: 'created_at', title: '上传时间', width: 120 },
  { colKey: 'operation', title: '操作', width: 220, fixed: 'right' as const },
]

function statusLabel(s: string) {
  return { pending: '等待中', parsing: '解析中', completed: '已完成', failed: '失败' }[s] || s
}
function statusTheme(s: string): any {
  return { pending: 'default', parsing: 'warning', completed: 'success', failed: 'danger' }[s] || 'default'
}
function formatDate(t: string) { return t ? new Date(t).toLocaleDateString('zh-CN') : '' }
function formatSize(bytes: number) {
  if (!bytes) return '-'
  if (bytes < 1024) return bytes + 'B'
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + 'KB'
  return (bytes / 1024 / 1024).toFixed(1) + 'MB'
}

async function loadDocuments() {
  loading.value = true
  try {
    const res = await listDocuments({
      space_id: spaceId.value || undefined,
      search: searchQuery.value || undefined,
      parse_status: statusFilter.value || undefined,
      page: currentPage.value,
      page_size: pageSize.value,
    })
    documents.value = (res.data as any).documents || []
    total.value = (res.data as any).total || 0
  } catch {
    documents.value = []
  } finally {
    loading.value = false
  }
}

async function handleDelete(row: Document) {
  try {
    await deleteDocument(row.id)
    MessagePlugin.success('文档已删除')
    loadDocuments()
  } catch {
    MessagePlugin.error('删除失败')
  }
}

async function handleReparse(row: Document) {
  try {
    await reparseDocument(row.id)
    MessagePlugin.success('已触发重新解析')
    loadDocuments()
  } catch {
    MessagePlugin.error('操作失败')
  }
}

async function viewChunks(row: Document) {
  showChunks.value = true
  chunksLoading.value = true
  try {
    const res = await getDocumentChunks(row.id)
    chunks.value = (res.data as any).chunks || []
  } catch {
    chunks.value = []
  } finally {
    chunksLoading.value = false
  }
}

function onRowClick(row: any) {
  viewChunks(row)
}

watch(spaceId, () => {
  if (spaceId.value) loadDocuments()
})

onMounted(() => {
  if (spaceId.value) loadDocuments()
})
</script>

<style scoped>
.docs-page { max-width: 1200px; margin: 0 auto; }
.docs-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; flex-wrap: wrap; gap: 12px; }
.header-left { display: flex; align-items: center; gap: 12px; }
.header-left h2 { font-size: 20px; font-weight: 600; color: var(--text-primary); }
.empty { text-align: center; padding: 80px 20px; }
.empty-title { font-size: 18px; font-weight: 500; margin: 16px 0 8px; color: var(--text-primary); }
.empty-desc { color: var(--text-secondary); margin-bottom: 24px; }
.pagination { margin-top: 16px; display: flex; justify-content: center; }
.muted-empty-icon { color: var(--text-muted); }
</style>
