// frontend/smartknora/src/views/spaces/SpacesPage.vue
<template>
  <div class="spaces-page">
    <div class="page-header">
      <h1>知识空间</h1>
      <t-button theme="primary" @click="showCreate = true">
        <template #icon><t-icon name="add" /></template>
        新建空间
      </t-button>
    </div>

    <t-loading v-if="loading" />
    <div v-else-if="spaces.length === 0" class="empty">
      <t-icon name="folder-open" size="64px" style="color:#d0d0d0" />
      <p class="empty-title">还没有知识空间</p>
      <p class="empty-desc">创建您的第一个知识空间，开始管理企业知识</p>
      <t-button theme="primary" @click="showCreate = true">创建知识空间</t-button>
    </div>
    <div v-else class="space-grid">
      <t-card
        v-for="space in spaces"
        :key="space.id"
        class="space-card"
        :title="space.name"
        :description="space.description || '暂无描述'"
        hover-shadow
        @click="goDetail(space.id)"
      >
        <template #actions>
          <t-button variant="text" theme="primary" @click.stop="goDetail(space.id)">
            <t-icon name="chevron-right" />
          </t-button>
        </template>
      </t-card>
    </div>

    <t-dialog v-model:visible="showCreate" header="创建知识空间" @confirm="handleCreate" :confirm-btn="{ loading: creating }">
      <t-form>
        <t-form-item label="空间名称" name="name">
          <t-input v-model="form.name" placeholder="请输入空间名称" :maxlength="30" />
        </t-form-item>
        <t-form-item label="空间描述" name="description">
          <t-textarea v-model="form.description" placeholder="选填" :autosize="{ minRows: 2 }" />
        </t-form-item>
        <t-form-item label="可见性" name="visibility">
          <t-select v-model="form.visibility">
            <t-option value="private" label="私密" />
            <t-option value="team" label="团队可见" />
            <t-option value="enterprise" label="企业可见" />
          </t-select>
        </t-form-item>
      </t-form>
    </t-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { listSpaces, createSpace, type Space } from '@/api/spaces'
import { MessagePlugin } from 'tdesign-vue-next'

const router = useRouter()
const spaces = ref<Space[]>([])
const loading = ref(true)
const showCreate = ref(false)
const creating = ref(false)
const form = ref({ name: '', description: '', visibility: 'private' })

async function load() {
  loading.value = true
  try {
    const res = await listSpaces()
    spaces.value = (res.data as any).spaces || []
  } catch { spaces.value = [] }
  finally { loading.value = false }
}

async function handleCreate() {
  if (!form.value.name) { MessagePlugin.warning('请输入空间名称'); return }
  creating.value = true
  try {
    await createSpace(form.value)
    MessagePlugin.success('创建成功')
    showCreate.value = false
    form.value = { name: '', description: '', visibility: 'private' }
    load()
  } catch (e: any) {
    MessagePlugin.error(e.response?.data?.error || '创建失败')
  } finally { creating.value = false }
}

function goDetail(id: string) {
  router.push(`/spaces/${id}`)
}

onMounted(load)
</script>

<style scoped>
.spaces-page { max-width: 1200px; margin: 0 auto; }
.page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }
.page-header h1 { font-size: 24px; font-weight: 600; }
.empty { text-align: center; padding: 80px 20px; }
.empty-title { font-size: 18px; font-weight: 500; margin: 16px 0 8px; }
.empty-desc { color: #999; margin-bottom: 24px; }
.space-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 16px; }
.space-card { cursor: pointer; }
</style>

// frontend/smartknora-react-backup/src/pages/spaces/SpacesPage.tsx
import { useEffect, useState } from 'react'
import { Card, Button, Row, Col, Dialog, Form, Input, Select, MessagePlugin } from 'tdesign-react'
import { useNavigate } from 'react-router-dom'
import { spaceApi } from '../../api/client'
import type { KnowledgeSpace } from '../../types'

export default function SpacesPage() {
  const navigate = useNavigate()
  const [spaces, setSpaces] = useState<KnowledgeSpace[]>([])
  const [showCreate, setShowCreate] = useState(false)
  const [newName, setNewName] = useState('')
  const [newDesc, setNewDesc] = useState('')
  const [newVisibility, setNewVisibility] = useState('team')

  const loadSpaces = () => {
    spaceApi.list().then(res => setSpaces(res.data.spaces || [])).catch((err) => { console.error('API error:', err) })
  }

  useEffect(() => { loadSpaces() }, [])

  const handleCreate = async () => {
    if (!newName.trim()) { MessagePlugin.error('请输入空间名称'); return }
    try {
      await spaceApi.create({ name: newName, description: newDesc, visibility: newVisibility })
      MessagePlugin.success('创建成功')
      setShowCreate(false)
      setNewName(''); setNewDesc(''); setNewVisibility('team')
      loadSpaces()
    } catch (err: any) {
      MessagePlugin.error(err?.response?.data?.error || '创建失败')
    }
  }

  const handleDelete = async (id: string, name: string) => {
    const confirmed = await Dialog.confirm({ header: '确认删除', body: `确定要删除知识空间「${name}」吗？` })
    if (confirmed) {
      try {
        await spaceApi.delete(id)
        MessagePlugin.success('已删除')
        loadSpaces()
      } catch (err: any) {
        MessagePlugin.error(err?.response?.data?.error || '删除失败')
      }
    }
  }

  return (
    <div style={{ padding: 24 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <h2 style={{ margin: 0 }}>📚 知识空间</h2>
        <Button theme="primary" onClick={() => setShowCreate(true)}>+ 创建空间</Button>
      </div>

      {spaces.length === 0 ? (
        <Card style={{ textAlign: 'center', padding: 60 }}>
          <p style={{ fontSize: 48, margin: 0 }}>📚</p>
          <p style={{ color: '#999', marginTop: 16 }}>还没有知识空间</p>
          <Button theme="primary" onClick={() => setShowCreate(true)}>创建第一个空间</Button>
        </Card>
      ) : (
        <Row gutter={16}>
          {spaces.map(space => (
            <Col key={space.id} span={8}>
              <Card
                hoverShadow
                style={{ cursor: 'pointer', marginBottom: 16 }}
                actions={
                  <Button variant="text" size="small" theme="danger"
                    onClick={(e) => { e.stopPropagation(); handleDelete(space.id, space.name) }}>
                    删除
                  </Button>
                }
              >
                <div onClick={() => navigate(`/spaces/${space.id}`)}>
                  <div style={{ fontSize: 18, fontWeight: 500 }}>{space.icon || '📚'} {space.name}</div>
                  <p style={{ color: '#999', fontSize: 13, marginTop: 8, minHeight: 40 }}>
                    {space.description || '暂无描述'}
                  </p>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 }}>
                    <span style={{ fontSize: 12, color: '#bbb' }}>
                      {space.visibility === 'private' ? '🔒 私密' : space.visibility === 'team' ? '👥 团队' : '🏢 企业'}
                    </span>
                    <span style={{ fontSize: 12, color: '#bbb' }}>
                      {new Date(space.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </div>
              </Card>
            </Col>
          ))}
        </Row>
      )}

      {/* Create Dialog */}
      <Dialog
        header="创建知识空间"
        visible={showCreate}
        onConfirm={handleCreate}
        onClose={() => setShowCreate(false)}
      >
        <Form>
          <Form.FormItem label="空间名称" required>
            <Input placeholder="请输入空间名称" value={newName} onChange={setNewName} />
          </Form.FormItem>
          <Form.FormItem label="描述">
            <Input placeholder="空间描述（选填）" value={newDesc} onChange={setNewDesc} />
          </Form.FormItem>
          <Form.FormItem label="可见性">
            <Select value={newVisibility} onChange={setNewVisibility} options={[
              { label: '🔒 私密（仅成员）', value: 'private' },
              { label: '👥 团队（组织内可见）', value: 'team' },
              { label: '🏢 企业（全企业可见）', value: 'org' },
            ]} />
          </Form.FormItem>
        </Form>
      </Dialog>
    </div>
  )
}
