// frontend/smartknora/src/views/qa/QAPage.vue
<template>
  <div class="qa-page">
    <div class="qa-sidebar">
      <div class="sidebar-header">
        <h3>AI 问答</h3>
        <t-button theme="primary" size="small" @click="handleNewSession">
          <template #icon><t-icon name="add" /></template>
          新对话
        </t-button>
      </div>
      <div class="session-list">
        <div
          v-for="s in sessions"
          :key="s.id"
          :class="['session-item', { active: s.id === currentSessionId }]"
          @click="switchSession(s.id)"
        >
          <t-icon name="chat" size="16px" />
          <span class="session-title">{{ s.title }}</span>
        </div>
        <div v-if="sessions.length === 0" class="no-sessions">暂无历史对话</div>
      </div>
    </div>

    <div class="qa-main">
      <div v-if="!currentSessionId" class="qa-welcome">
        <t-icon name="chat" size="64px" style="color:#d0d0d0" />
        <h2>开始 AI 问答</h2>
        <p>选择知识空间，创建新对话，向知识库提问</p>
        <t-button theme="primary" size="large" @click="handleNewSession">
          <template #icon><t-icon name="add" /></template>
          新建对话
        </t-button>
      </div>

      <template v-else>
        <div class="messages-area" ref="msgArea">
          <div v-for="msg in messages" :key="msg.id" :class="['msg-row', msg.role]">
            <div class="msg-avatar">
              <t-icon :name="msg.role === 'user' ? 'user' : 'robot'" size="24px" />
            </div>
            <div class="msg-bubble">
              <div class="msg-content">{{ msg.content }}</div>
              <div v-if="msg.role === 'assistant' && msg.sources && msg.sources !== '[]'" class="msg-sources">
                <t-tag theme="primary" variant="light" size="small">📎 引用来源</t-tag>
              </div>
            </div>
          </div>
          <div v-if="sending" class="msg-row assistant">
            <div class="msg-avatar"><t-icon name="robot" size="24px" /></div>
            <div class="msg-bubble"><t-loading size="small" /></div>
          </div>
        </div>

        <div class="input-area">
          <t-textarea
            v-model="inputText"
            placeholder="输入您的问题..."
            :autosize="{ minRows: 1, maxRows: 4 }"
            @enter="handleSend"
            :disabled="sending"
          />
          <t-button theme="primary" :loading="sending" :disabled="!inputText.trim()" @click="handleSend">
            <template #icon><t-icon name="send" /></template>
            发送
          </t-button>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, nextTick } from 'vue'
import { listSessions, createSession, getMessages, sendMessage, type QASession, type QAMessage } from '@/api/qa'
import { MessagePlugin } from 'tdesign-vue-next'

const sessions = ref<QASession[]>([])
const currentSessionId = ref('')
const messages = ref<QAMessage[]>([])
const inputText = ref('')
const sending = ref(false)
const msgArea = ref<HTMLElement>()

async function loadSessions() {
  try {
    const res = await listSessions()
    sessions.value = (res.data as any).sessions || []
  } catch { sessions.value = [] }
}

async function handleNewSession() {
  try {
    const res = await createSession({ title: '新对话' })
    const session = (res.data as any).session
    sessions.value.unshift(session)
    currentSessionId.value = session.id
    messages.value = []
  } catch { MessagePlugin.error('创建会话失败') }
}

async function switchSession(id: string) {
  currentSessionId.value = id
  try {
    const res = await getMessages(id)
    messages.value = (res.data as any).messages || []
    scrollToBottom()
  } catch { messages.value = [] }
}

async function handleSend() {
  if (!inputText.value.trim() || !currentSessionId.value) return
  const text = inputText.value.trim()
  inputText.value = ''
  sending.value = true

  // 立即显示用户消息
  messages.value.push({
    id: 'temp-' + Date.now(),
    session_id: currentSessionId.value,
    role: 'user',
    content: text,
    sources: '[]',
    created_at: new Date().toISOString(),
  })
  scrollToBottom()

  try {
    const res = await sendMessage(currentSessionId.value, text)
    const data = res.data as any
    messages.value.push(data.assistant_message)
    scrollToBottom()
  } catch {
    MessagePlugin.error('发送失败')
  } finally {
    sending.value = false
  }
}

function scrollToBottom() {
  nextTick(() => {
    if (msgArea.value) msgArea.value.scrollTop = msgArea.value.scrollHeight
  })
}

onMounted(loadSessions)
</script>

<style scoped>
.qa-page { display: flex; height: calc(100vh - 104px); background: #fff; border-radius: 8px; overflow: hidden; }
.qa-sidebar { width: 260px; border-right: 1px solid #e7e7e7; display: flex; flex-direction: column; }
.sidebar-header { display: flex; justify-content: space-between; align-items: center; padding: 16px; border-bottom: 1px solid #f0f0f0; }
.sidebar-header h3 { font-size: 16px; font-weight: 600; }
.session-list { flex: 1; overflow-y: auto; padding: 8px; }
.session-item { display: flex; align-items: center; gap: 8px; padding: 10px 12px; border-radius: 6px; cursor: pointer; font-size: 14px; color: #333; margin-bottom: 2px; }
.session-item:hover { background: #f5f5f5; }
.session-item.active { background: #e8f0ff; color: #014DB2; }
.session-title { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.no-sessions { text-align: center; padding: 24px; color: #ccc; font-size: 13px; }
.qa-main { flex: 1; display: flex; flex-direction: column; }
.qa-welcome { flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 12px; color: #999; }
.qa-welcome h2 { font-size: 22px; color: #333; }
.messages-area { flex: 1; overflow-y: auto; padding: 24px; }
.msg-row { display: flex; gap: 12px; margin-bottom: 20px; }
.msg-avatar { width: 36px; height: 36px; border-radius: 50%; display: flex; align-items: center; justify-content: center; flex-shrink: 0; background: #f0f2f5; color: #666; }
.msg-row.user .msg-avatar { background: #014DB2; color: #fff; }
.msg-bubble { max-width: 70%; padding: 12px 16px; border-radius: 12px; font-size: 14px; line-height: 1.6; }
.msg-row.user .msg-bubble { background: #014DB2; color: #fff; border-bottom-right-radius: 4px; }
.msg-row.assistant .msg-bubble { background: #f5f5f5; color: #333; border-bottom-left-radius: 4px; }
.msg-content { white-space: pre-wrap; }
.msg-sources { margin-top: 8px; }
.input-area { display: flex; gap: 12px; padding: 16px 24px; border-top: 1px solid #e7e7e7; align-items: flex-end; }
.input-area :deep(.t-textarea) { flex: 1; }
</style>

// frontend/smartknora/src/pages/qa/QAPage.tsx
import { useEffect, useState, useRef } from 'react'
import { Card, Button, Input, List, Tag, Avatar, MessagePlugin } from 'tdesign-react'
import client from '../../api/client'

interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  created_at: string
}

interface Session {
  id: string
  title: string
  updated_at: string
}

export default function QAPage() {
  const [sessions, setSessions] = useState<Session[]>([])
  const [currentSession, setCurrentSession] = useState<string | null>(null)
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [sending, setSending] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    client.get('/qa/sessions').then(res => setSessions(res.data.sessions || [])).catch((err) => { console.error('API error:', err) })
  }, [])

  useEffect(() => {
    if (currentSession) {
      client.get(`/qa/sessions/${currentSession}/messages`)
        .then(res => setMessages(res.data.messages || []))
        .catch((err) => { console.error('API error:', err) })
    }
  }, [currentSession])

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])

  const handleNewSession = async () => {
    try {
      const res = await client.post('/qa/sessions', { title: '新对话' })
      const session = res.data.session
      setSessions(prev => [session, ...prev])
      setCurrentSession(session.id)
    } catch (err: any) {
      MessagePlugin.error(err?.response?.data?.error || '创建会话失败')
    }
  }

  const handleSend = async () => {
    if (!input.trim() || !currentSession || sending) return
    setSending(true)
    const content = input
    setInput('')

    try {
      const res = await client.post(`/qa/sessions/${currentSession}/messages`, { content })
      setMessages(prev => [...prev, res.data.user_message, res.data.assistant_message])
    } catch (err: any) {
      // Show error as system message
      setMessages(prev => [...prev, {
        id: Date.now().toString(),
        role: 'assistant',
        content: '抱歉，发生了错误：' + (err?.response?.data?.error || '未知错误'),
        created_at: new Date().toISOString()
      }])
    } finally {
      setSending(false)
    }
  }

  return (
    <div style={{ display: 'flex', height: '100%' }}>
      {/* Session sidebar */}
      <div style={{ width: 280, borderRight: '1px solid #e8e8e8', background: '#fafafa', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: 16, borderBottom: '1px solid #e8e8e8' }}>
          <Button theme="primary" block onClick={handleNewSession}>+ 新对话</Button>
        </div>
        <div style={{ flex: 1, overflow: 'auto' }}>
          {sessions.map(s => (
            <div
              key={s.id}
              onClick={() => setCurrentSession(s.id)}
              style={{
                padding: '12px 16px',
                cursor: 'pointer',
                background: currentSession === s.id ? '#e8f4ff' : 'transparent',
                borderBottom: '1px solid #f0f0f0',
              }}
            >
              <div style={{ fontSize: 14, fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {s.title}
              </div>
              <div style={{ fontSize: 12, color: '#999', marginTop: 4 }}>
                {new Date(s.updated_at).toLocaleDateString()}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Chat area */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        {/* Header */}
        <div style={{ padding: '16px 24px', borderBottom: '1px solid #e8e8e8', background: '#fff' }}>
          <h3 style={{ margin: 0 }}>🤖 AI 问答</h3>
        </div>

        {/* Messages */}
        <div style={{ flex: 1, overflow: 'auto', padding: 24, background: '#f8f9fa' }}>
          {messages.length === 0 ? (
            <div style={{ textAlign: 'center', color: '#999', paddingTop: 100 }}>
              <p style={{ fontSize: 48 }}>🤖</p>
              <p>开始提问，AI 将基于知识库回答</p>
            </div>
          ) : (
            messages.map(msg => (
              <div key={msg.id} style={{
                display: 'flex',
                justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start',
                marginBottom: 16,
              }}>
                <div style={{
                  maxWidth: '70%',
                  padding: '12px 16px',
                  borderRadius: 12,
                  background: msg.role === 'user' ? '#0052D9' : '#fff',
                  color: msg.role === 'user' ? '#fff' : '#333',
                  boxShadow: msg.role === 'assistant' ? '0 1px 3px rgba(0,0,0,0.1)' : 'none',
                }}>
                  {msg.content}
                </div>
              </div>
            ))
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div style={{ padding: 16, borderTop: '1px solid #e8e8e8', background: '#fff', display: 'flex', gap: 12 }}>
          <Input
            placeholder="输入问题..."
            value={input}
            onChange={setInput}
            onPressEnter={handleSend}
            disabled={!currentSession || sending}
            size="large"
          />
          <Button
            theme="primary"
            onClick={handleSend}
            loading={sending}
            disabled={!currentSession || !input.trim()}
            size="large"
          >
            发送
          </Button>
        </div>
      </div>
    </div>
  )
}
