// frontend/smartknora/src/views/writing/WritingPage.vue
<template>
  <div class="writing-page">
    <div class="writing-sidebar">
      <div class="sidebar-header">
        <h3>AI 写作</h3>
        <t-button theme="primary" size="small" @click="showNew = true">
          <template #icon><t-icon name="add" /></template>
          新建
        </t-button>
      </div>
      <div class="draft-list">
        <div v-for="d in drafts" :key="d.id" :class="['draft-item', { active: d.id === currentId }]" @click="loadDraft(d.id)">
          <t-icon name="file-paste" size="16px" />
          <div class="draft-info">
            <span class="draft-title">{{ d.title }}</span>
            <span class="draft-cat">{{ categoryLabel(d.category) }}</span>
          </div>
        </div>
        <div v-if="drafts.length === 0" class="no-drafts">暂无草稿</div>
      </div>
    </div>

    <div class="writing-main">
      <div v-if="!currentDraft" class="welcome">
        <t-icon name="edit" size="64px" style="color:#d0d0d0" />
        <h2>AI 写作辅助</h2>
        <p>选择写作类别，输入主题，AI 将基于知识库生成内容</p>
        <t-button theme="primary" size="large" @click="showNew = true">
          <template #icon><t-icon name="add" /></template>
          开始写作
        </t-button>
      </div>

      <template v-else>
        <div class="editor-header">
          <t-input v-model="currentDraft.title" placeholder="文档标题" size="large" @blur="saveDraft" />
          <t-space>
            <t-select v-model="exportFormat" style="width:100px">
              <t-option value="markdown" label="Markdown" />
              <t-option value="docx" label="Word" />
              <t-option value="pdf" label="PDF" />
            </t-select>
            <t-button variant="outline" @click="handleExport">
              <template #icon><t-icon name="download" /></template>
              导出
            </t-button>
          </t-space>
        </div>
        <t-textarea v-model="currentDraft.content" :autosize="{ minRows: 15, maxRows: 30 }" placeholder="在此编辑内容..." class="editor-textarea" @blur="saveDraft" />
      </template>
    </div>

    <t-dialog v-model:visible="showNew" header="AI 写作" :footer="false" width="560px">
      <div class="new-form">
        <t-form label-align="top">
          <t-form-item label="写作类别" name="category">
            <t-select v-model="newForm.category" size="large">
              <t-option v-for="c in CATEGORIES" :key="c.value" :value="c.value" :label="c.label" />
            </t-select>
          </t-form-item>
          <t-form-item label="主题/提示词" name="prompt">
            <t-input v-model="newForm.prompt" placeholder="例如：2026年Q2技术团队工作总结" size="large" />
          </t-form-item>
          <t-form-item label="知识来源（选填）" name="space_id">
            <t-select v-model="newForm.space_id" placeholder="选择知识空间（留空则搜索全部）" clearable size="large">
              <t-option v-for="s in spaces" :key="s.id" :value="s.id" :label="s.name" />
            </t-select>
          </t-form-item>
        </t-form>
        <t-button theme="primary" block size="large" :loading="generating" :disabled="!newForm.category || !newForm.prompt" @click="handleGenerate">
          <template #icon><t-icon name="magic" /></template>
          AI 生成
        </t-button>
      </div>
    </t-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { generateContent, createDraft, listDrafts, getDraft, updateDraft, exportDraft, CATEGORIES, type WritingDraft } from '@/api/writing'
import { listSpaces, type Space } from '@/api/spaces'
import { MessagePlugin } from 'tdesign-vue-next'

const drafts = ref<WritingDraft[]>([])
const spaces = ref<Space[]>([])
const currentId = ref('')
const currentDraft = ref<WritingDraft | null>(null)
const showNew = ref(false)
const generating = ref(false)
const newForm = ref({ category: 'work_summary', prompt: '', space_id: '' })
const exportFormat = ref('markdown')

function categoryLabel(v: string) { return CATEGORIES.find(c => c.value === v)?.label || v }

async function loadDrafts() {
  try { const res = await listDrafts(); drafts.value = (res.data as any).drafts || [] } catch { drafts.value = [] }
}
async function loadSpaces() {
  try { const res = await listSpaces(); spaces.value = (res.data as any).spaces || [] } catch { spaces.value = [] }
}

async function loadDraft(id: string) {
  currentId.value = id
  try { const res = await getDraft(id); currentDraft.value = (res.data as any).draft } catch { MessagePlugin.error('加载失败') }
}

async function handleGenerate() {
  generating.value = true
  try {
    const genRes = await generateContent(newForm.value)
    const content = (genRes.data as any).content
    const sourcesCount = (genRes.data as any).sources_count || 0

    const draftRes = await createDraft({ title: newForm.value.prompt, category: newForm.value.category, space_id: newForm.value.space_id })
    const draft = (draftRes.data as any).draft
    await updateDraft(draft.id, { title: newForm.value.prompt, content, status: 'draft' })
    draft.content = content
    drafts.value.unshift(draft)
    currentId.value = draft.id
    currentDraft.value = draft
    showNew.value = false
    newForm.value = { category: 'work_summary', prompt: '', space_id: '' }
    MessagePlugin.success(`生成完成${sourcesCount > 0 ? `（引用 ${sourcesCount} 条知识）` : ''}`)
    loadDrafts()
  } catch (e: any) { MessagePlugin.error(e.response?.data?.error || '生成失败') }
  finally { generating.value = false }
}

async function saveDraft() {
  if (!currentDraft.value) return
  try {
    await updateDraft(currentDraft.value.id, { title: currentDraft.value.title, content: currentDraft.value.content })
  } catch {}
}

async function handleExport() {
  if (!currentDraft.value) return
  try {
    await exportDraft(currentDraft.value.id, exportFormat.value)
    MessagePlugin.success('导出已启动')
  } catch { MessagePlugin.error('导出失败') }
}

onMounted(() => { loadDrafts(); loadSpaces() })
</script>

<style scoped>
.writing-page { display: flex; height: calc(100vh - 104px); background: #fff; border-radius: 8px; overflow: hidden; }
.writing-sidebar { width: 260px; border-right: 1px solid #e7e7e7; display: flex; flex-direction: column; }
.sidebar-header { display: flex; justify-content: space-between; align-items: center; padding: 16px; border-bottom: 1px solid #f0f0f0; }
.sidebar-header h3 { font-size: 16px; font-weight: 600; }
.draft-list { flex: 1; overflow-y: auto; padding: 8px; }
.draft-item { display: flex; gap: 8px; padding: 10px 12px; border-radius: 6px; cursor: pointer; margin-bottom: 2px; }
.draft-item:hover { background: #f5f5f5; }
.draft-item.active { background: #e8f0ff; color: #014DB2; }
.draft-info { display: flex; flex-direction: column; }
.draft-title { font-size: 14px; font-weight: 500; }
.draft-cat { font-size: 12px; color: #999; }
.no-drafts { text-align: center; padding: 24px; color: #ccc; font-size: 13px; }
.writing-main { flex: 1; display: flex; flex-direction: column; padding: 24px; overflow-y: auto; }
.welcome { flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 12px; color: #999; }
.welcome h2 { font-size: 22px; color: #333; }
.editor-header { display: flex; gap: 12px; margin-bottom: 16px; align-items: center; }
.editor-header :deep(.t-input) { flex: 1; }
.editor-textarea { flex: 1; }
.new-form { padding: 16px 0; display: flex; flex-direction: column; gap: 16px; }
</style>

// frontend/smartknora-react-backup/src/pages/writing/WritingPage.tsx
import { useState, useEffect } from 'react'
import { Card, Button, Input, Select, MessagePlugin, Tabs } from 'tdesign-react'
import client from '../../api/client'

const CATEGORIES = [
  { value: 'work_summary', label: '📝 工作总结' },
  { value: 'research_report', label: '📊 研究报告' },
  { value: 'project_plan', label: '📋 项目方案' },
  { value: 'meeting_notes', label: '📓 会议纪要' },
  { value: 'tech_doc', label: '📘 技术文档' },
  { value: 'business_plan', label: '📈 商业计划书' },
  { value: 'daily_report', label: '📅 周报日报' },
]

export default function WritingPage() {
  const [category, setCategory] = useState('work_summary')
  const [prompt, setPrompt] = useState('')
  const [content, setContent] = useState('')
  const [generating, setGenerating] = useState(false)
  const [title, setTitle] = useState('')
  const [activeTab, setActiveTab] = useState('write')

  const handleGenerate = async () => {
    if (!prompt.trim()) { MessagePlugin.error('请输入写作提示'); return }
    setGenerating(true)
    try {
      const res = await client.post('/writing/generate', { category, prompt })
      setContent(res.data.content)
      MessagePlugin.success('内容生成完成')
    } catch (err: any) {
      MessagePlugin.error(err?.response?.data?.error || '生成失败')
    } finally {
      setGenerating(false)
    }
  }

  const handleSave = async () => {
    if (!title.trim()) { MessagePlugin.error('请输入标题'); return }
    try {
      await client.post('/writing/drafts', { title, category, content })
      MessagePlugin.success('草稿已保存')
    } catch (err: any) {
      MessagePlugin.error(err?.response?.data?.error || '保存失败')
    }
  }

  return (
    <div style={{ padding: 24 }}>
      <h2 style={{ marginBottom: 24 }}>✍️ AI 写作助手</h2>

      <Tabs value={activeTab} onChange={setActiveTab}>
        <Tabs.TabPanel value="write" label="写作工作台">
          <div style={{ display: 'flex', gap: 24, marginTop: 16 }}>
            {/* Left panel - category & prompt */}
            <Card style={{ width: 320 }}>
              <h4 style={{ marginBottom: 16 }}>选择写作类别</h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 24 }}>
                {CATEGORIES.map(cat => (
                  <Button
                    key={cat.value}
                    variant={category === cat.value ? 'base' : 'outline'}
                    onClick={() => setCategory(cat.value)}
                    block
                  >
                    {cat.label}
                  </Button>
                ))}
              </div>

              <h4 style={{ marginBottom: 8 }}>写作提示</h4>
              <Input.Textarea
                placeholder="描述您想写的内容..."
                value={prompt}
                onChange={setPrompt}
                rows={4}
                style={{ marginBottom: 16 }}
              />

              <Button
                theme="primary"
                block
                onClick={handleGenerate}
                loading={generating}
              >
                🤖 AI 生成
              </Button>
            </Card>

            {/* Right panel - content editor */}
            <Card style={{ flex: 1 }}>
              <div style={{ marginBottom: 16 }}>
                <Input
                  placeholder="文档标题"
                  value={title}
                  onChange={setTitle}
                  size="large"
                  style={{ fontSize: 18 }}
                />
              </div>

              <Input.Textarea
                placeholder="AI 生成的内容将显示在这里，您也可以直接编辑..."
                value={content}
                onChange={setContent}
                rows={20}
                style={{ marginBottom: 16, fontFamily: 'monospace' }}
              />

              <div style={{ display: 'flex', gap: 12 }}>
                <Button theme="primary" onClick={handleSave}>💾 保存草稿</Button>
                <Button variant="outline" disabled title="即将推出">📤 导出 PDF</Button>
                <Button variant="outline" disabled title="即将推出">📤 导出 DOCX</Button>
                <Button variant="outline" disabled title="即将推出">📤 导出 Markdown</Button>
              </div>
            </Card>
          </div>
        </Tabs.TabPanel>

        <Tabs.TabPanel value="drafts" label="草稿箱">
          <DraftsList />
        </Tabs.TabPanel>
      </Tabs>
    </div>
  )
}

function DraftsList() {
  const [drafts, setDrafts] = useState<any[]>([])

  useEffect(() => {
    client.get('/writing/drafts').then(res => setDrafts(res.data.drafts || [])).catch((err) => { console.error('API error:', err) })
  }, [])

  return (
    <div style={{ marginTop: 16 }}>
      {drafts.length === 0 ? (
        <Card style={{ textAlign: 'center', padding: 60 }}>
          <p style={{ fontSize: 48 }}>📝</p>
          <p style={{ color: '#999' }}>暂无草稿</p>
        </Card>
      ) : (
        drafts.map(draft => (
          <Card key={draft.id} style={{ marginBottom: 12 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <div style={{ fontSize: 16, fontWeight: 500 }}>{draft.title || '无标题'}</div>
                <div style={{ fontSize: 13, color: '#999', marginTop: 4 }}>
                  {draft.category} · {new Date(draft.updated_at).toLocaleString()}
                </div>
              </div>
              <Button size="small" variant="outline" disabled title="即将推出">编辑</Button>
            </div>
          </Card>
        ))
      )}
    </div>
  )
}
